// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function Button(Props) {
  var size = Props.size;
  var onClick = Props.onClick;
  var children = Props.children;
  var tmp;
  switch (size) {
    case /* Default */0 :
        tmp = "20px";
        break;
    case /* Large */1 :
        tmp = "30px";
        break;
    case /* Small */2 :
        tmp = "10px";
        break;
    
  }
  return React.createElement("button", {
              style: {
                height: tmp
              },
              onClick: onClick
            }, children);
}

function makeProps(param, param$1, param$2, param$3) {
  var tmp = {
    size: /* Large */1,
    onClick: param,
    children: param$1
  };
  if (param$2 !== undefined) {
    tmp.key = Caml_option.valFromOption(param$2);
  }
  return tmp;
}

var Large = {
  make: Button,
  makeProps: makeProps
};

var make = Button;

exports.make = make;
exports.Large = Large;
/* react Not a pure module */
