// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Button = require("./Button.bs.js");

function Component1(Props) {
  var greeting = Props.greeting;
  var match = React.useReducer((function (state, action) {
          if (action) {
            return {
                    count: state.count,
                    show: !state.show
                  };
          } else {
            return {
                    count: state.count + 1 | 0,
                    show: state.show
                  };
          }
        }), {
        count: 0,
        show: true
      });
  var dispatch = match[1];
  var state = match[0];
  var message = "You've clicked this " + (String(state.count) + " times(s)");
  return React.createElement("div", undefined, React.createElement(Button.make, {
                  size: /* Default */0,
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Click */0);
                    }),
                  children: message
                }), React.createElement(Button.Large.make, Button.Large.makeProps((function (_event) {
                        return Curry._1(dispatch, /* Toggle */1);
                      }), "Toggle greeting", undefined, undefined)), state.show ? greeting : null);
}

var make = Component1;

exports.make = make;
/* react Not a pure module */
