// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function makeProps(firstName, lastName, param) {
  return {
          firstName: firstName,
          lastName: lastName
        };
}

function make(props) {
  return React.createElement("div", undefined, props.firstName);
}

exports.makeProps = makeProps;
exports.make = make;
/* react Not a pure module */
